-- Q1. revenue generated by male vs female customers 
with revenue_cte as (
select
	gender,
	sum(purchase_amount) as revenue_by_gender
from customers
group by gender
)
select
	gender,
	revenue_by_gender,
	round((revenue_by_gender*100)/(sum(revenue_by_gender) over()),2) as revenue_percentage
from revenue_cte
order by revenue_percentage desc;


-- Q2. customers used a discount but still spent more than average purchase amout
select
customer_id,purchase_amount
from customers
where lower(discount_applied) = 'yes' 
and purchase_amount > (
					select
					avg(purchase_amount)
					from customers);
                    
-- Q3. identity the top 5 products with the highest average review rating

with avg_review_rank as (
	select
	item_purchased,
    avg_review_rating,
	dense_rank() over(order by avg_review_rating) as rnk
	from (
		select
		item_purchased,
		round(avg(review_rating),2) as avg_review_rating
		from customers
		group by item_purchased
		order by avg_review_rating desc) 
    as t
) 
select 
	item_purchased,
    avg_review_rating
from avg_review_rank
where rnk <=5;


-- Q4.compare the average purchase amounts between standard and express shipping

select
shipping_type,
round(avg(purchase_amount),2) as revenue
from customers
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select
	subscription_status,
	count(customer_id) as total_customers,
	round(avg(purchase_amount),2) as avg_spend,
	sum(purchase_amount) as total_revenue
from customers
group by subscription_status
order by avg_spend,total_revenue;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select
	item_purchased,
	round(100*sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*),2) as purchase_discount_applied_pct
from customers
group by item_purchased
order by purchase_discount_applied_pct desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as (
	select
	customer_id,
	previous_purchases,
	case when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal' end as customer_segment
from customers
)
select
	customer_segment,
	count(*) as number_of_customers
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 

with items_count as (
	select
	category,
	item_purchased,
	count(customer_id) as total_orders,
	row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customers
group by category,item_purchased
) 
select
	item_rank,
	category,
	item_purchased,
	total_orders
from items_count
where item_rank<=3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select
	subscription_status,
	count(customer_id) as repeat_buyers
from customers
where previous_purchases >5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
with age_group_revenue as (
select
	age_group,
	sum(purchase_amount) as total_revenue
from customers
group by age_group
order by total_revenue desc
)
select
	age_group,
	total_revenue,
	round((total_revenue / sum(total_revenue) over())*100,2) as revenue_percentage
from age_group_revenue;















